// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/struct.proto

package proto

import proto1 "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto1.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type RequestStruct struct {
	Name string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
}

func (m *RequestStruct) Reset()                    { *m = RequestStruct{} }
func (m *RequestStruct) String() string            { return proto1.CompactTextString(m) }
func (*RequestStruct) ProtoMessage()               {}
func (*RequestStruct) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{0} }

func (m *RequestStruct) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type ReplyStruct struct {
	Message string `protobuf:"bytes,1,opt,name=message" json:"message,omitempty"`
}

func (m *ReplyStruct) Reset()                    { *m = ReplyStruct{} }
func (m *ReplyStruct) String() string            { return proto1.CompactTextString(m) }
func (*ReplyStruct) ProtoMessage()               {}
func (*ReplyStruct) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{1} }

func (m *ReplyStruct) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func init() {
	proto1.RegisterType((*RequestStruct)(nil), "proto.RequestStruct")
	proto1.RegisterType((*ReplyStruct)(nil), "proto.ReplyStruct")
}

func init() { proto1.RegisterFile("proto/struct.proto", fileDescriptor1) }

var fileDescriptor1 = []byte{
	// 104 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x2a, 0x28, 0xca, 0x2f,
	0xc9, 0xd7, 0x2f, 0x2e, 0x29, 0x2a, 0x4d, 0x2e, 0xd1, 0x03, 0x73, 0x84, 0x58, 0xc1, 0x94, 0x92,
	0x32, 0x17, 0x6f, 0x50, 0x6a, 0x61, 0x69, 0x6a, 0x71, 0x49, 0x30, 0x58, 0x56, 0x48, 0x88, 0x8b,
	0x25, 0x2f, 0x31, 0x37, 0x55, 0x82, 0x51, 0x81, 0x51, 0x83, 0x33, 0x08, 0xcc, 0x56, 0x52, 0xe7,
	0xe2, 0x0e, 0x4a, 0x2d, 0xc8, 0xa9, 0x84, 0x2a, 0x91, 0xe0, 0x62, 0xcf, 0x4d, 0x2d, 0x2e, 0x4e,
	0x4c, 0x87, 0xa9, 0x82, 0x71, 0x93, 0xd8, 0xc0, 0x86, 0x1a, 0x03, 0x02, 0x00, 0x00, 0xff, 0xff,
	0xb3, 0xcd, 0xc9, 0x3c, 0x71, 0x00, 0x00, 0x00,
}
